### ISSUE TITLE
rendering of img tags

### ISSUE THREAD

**Issue by g14a** [charmbracelet/glamour#111]
Does the library indicate that there is an image in the markdown at the specific location? basically img tags

**Comment by g14a** [comment]
This is my simple program and it renders only the first line.  Is there anything I'm missing?

```
package main

import (
	"fmt"
	"github.com/charmbracelet/glamour"
)

func main() {
	in := `first comment

<img width="807" alt="Screenshot 2021-03-31 at 9 43 00 AM" src="https://user-images.githubusercontent.com/17702388/113185693-626b6880-9274-11eb-96ae-ba8661b7e312.png">`

	out, err := glamour.Render(in, "dark")
	if err != nil {
		fmt.Println(err)
	}
      
        fmt.Println(out)
}
```

<img width="562" alt="image" src="https://user-images.githubusercontent.com/17702388/113188454-b035a000-9277-11eb-92c1-8b8cddca906d.png">

**Comment by meowgorithm** [comment]
Glamour doesn't parse HTML. For images you'll need to use [Markdown's image syntax](https://commonmark.org/help/).
