### ISSUE TITLE
Link Styles Not Working

### ISSUE THREAD

**Issue by Debdut** [charmbracelet/glamour#126]
##  Description
The links are not colored or styled properly.

##  How To Replicate
The showcase program at the beginning of README doesn't render the links correctly as show in the below it.

```go
func main() {
  in := `# Hello World

  This is a simple example of Markdown rendering with Glamour!
  Check out the [other examples (https://github.com/charmbracelet/glamour/tree/master/examples) too.
	
  Bye!
  `
  out, _ := glamour.Render(in, "dark")
  fmt.Print(out)
}
```
## Output
<img width="534" alt="Screen Shot 2021-11-06 at 12 21 26 AM" src="https://user-images.githubusercontent.com/7561070/140563410-5ad2c264-9951-4b89-a425-d38d27b7c505.png">

##  Expected Output
<img src="https://raw.githubusercontent.com/charmbracelet/glamour/master/examples/helloworld/helloworld.png">

**Comment by muesli** [comment]
I'm not sure this is actually a bug, as the indentation in markdowns has a meaning, it identifies code blocks: https://spec.commonmark.org/0.30/#indented-code-blocks
