### ISSUE TITLE
Markdown is awesome, but have you considered supporting AsciiDoc?

### ISSUE THREAD

**Issue by skatkov** [charmbracelet/glamour#164]
Really loving the project, use it often with Glow and even in my own side-projects.

I got a bit tired of all different implementations of Markdown and some missing features and started moving documentation in my repo's to AsciiDoc. It was a bummer to see, that Glow doesn't work with those.

So, it might be something that is already on your radar, but have you considered if asciidoc could be supported by glamour as well?

**Comment by muesli** [comment]
That would probably require a different parser (even though we could adapt parts of glamour's renderer). As such it's probably out of scope for `glamour` itself, but we have a separate issue requesting AsciiDoc support in `glow`'s repository. Thanks for creating the issue!
