### ISSUE TITLE
[Bug] escaped character not showing properly

### ISSUE THREAD

**Issue by developomp** [charmbracelet/glamour#169]
**How to reproduce**
escape a special character in the markdown file

example:
```
this is an asterisk: \*
```

**Expected result**
it escapes the asterisk character to render this:

```
this is an asterisk: *
```

**Actual result**
glow does not escape the asterisk character

```
this is an asterisk: \*
```

**Comment by muesli** [comment]
Thanks for reporting this! I'm currently consolidating a few tickets and will close this as it's already tracked in #106.
