### ISSUE TITLE
Word wrap is broken in quotes

### ISSUE THREAD

**Issue by parabolapersuader** [charmbracelet/glamour#171]
![glow](https://user-images.githubusercontent.com/86923324/128577455-119bc42f-b95e-4fbe-87bb-98ca6e931ed0.jpg)

In fact, that is a single line, a greater sign to mark the quote, a space, and the whole phrase unbroken. Yet glow can't handle THREE words in this single paragraph.

**Comment by muesli** [comment]
Closing as dupe of #172.
