### ISSUE TITLE
Broken link rendering in case of now link text

### ISSUE THREAD

**Issue by bitSchleuder** [charmbracelet/glamour#176]
Using solely the following link markup:
```
<https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html>
```
will lead to a broken link rendering with the latest glow. The link will be wrapped after "...-application-" by an underscore '_' (grey) as you can see in the screenshot
<img width="799" alt="Bildschirmfoto 2022-10-11 um 17 32 26" src="https://user-images.githubusercontent.com/1516036/195135608-c2062aeb-7b16-4296-a575-2f0eae1d46d0.png">

**Comment by muesli** [comment]
Dupe of #149.

**Comment by eiwja2222** [comment]
ผู้ไม่มีสิทธิ์ส่วนได้ส่วนเสียใดๆของบัญชีนี้คุณถูกออกโดยบังคับใช้โดยกฎหมายคุ้มครองส่วนบุคคลสหภาพยุโรปของกฎหมาย"PDPA"และกฎหมายคุ้มครองสิทธิส่วนบุคคลสหราชอณาจักรอังกฤษที่บังคับใช้.
