### ISSUE TITLE
please highlight code blocks with the same background style as inline code

### ISSUE THREAD

**Issue by john-soda** [charmbracelet/glamour#188]
Inline code can be recognized very well. Can you do the same background style as default for Code blocks?

I like the syntax highlighting feature when you specify the language for the Code block, but when you have for e.g. bash code like this where nothing is highlighted.
```bash
 sudo lvresize -l +100%FREE -r VG/L
```
it's very difficult to see in a longer document.

**Comment by muesli** [comment]
Closing as dupe of #181.
