### ISSUE TITLE
glamour render panics for too long lines

### ISSUE THREAD

**Issue by georgettica** [charmbracelet/glamour#198]
as seen in https://github.com/dnnrly/httpref/actions/runs/3303174571/jobs/5450794529 (related to https://github.com/dnnrly/httpref/pull/38)

glamour throws a panic when passing a line which is too long.

**Comment by muesli** [comment]
That's not a bug in glamour. You're calling `Render` on a nil `*glamour.TermRenderer`, called `descriptionStyle`.

**Comment by muesli** [comment]
Nothing to apologize for, these things happen. Keep up the great work!
