### ISSUE TITLE
Code block does not show content

### ISSUE THREAD

**Issue by fzdwx** [charmbracelet/glamour#201]
test data is https://github.com/charmbracelet/glamour/blob/master/testdata/example.md

```go
package main

import (
	"fmt"
	"github.com/charmbracelet/glamour"
	"io"
	"os"
)

func main() {
	r, err := os.Open("example.md")
	if err != nil {
		panic(err)
	}

	bytes, err := io.ReadAll(r)
	if err != nil {
		panic(err)
	}

	out, err := glamour.Render(string(bytes), "dark")
	if err != nil {
		panic(err)
	}

	fmt.Print(out)
}
```

![image](https://user-images.githubusercontent.com/65269574/200099488-fecb4816-0952-4a4b-9840-0050e0bb6147.png)

but when i use `glow` it is normal again:

![image](https://user-images.githubusercontent.com/65269574/200099525-3806dfc6-e251-4ee8-af74-b23594c3a027.png)

**Comment by fzdwx** [comment]
... I don't know why it's working right now，sorry.

**Comment by fzdwx** [comment]
There is one dependency that is different, I just found it
With `github.com/muesli/termenv v0.11.1-0.20220212125758-44cd13922739` this version is fine, and then with `github.com/muesli/termenv v0.13.0` there is a code block rendering problem.

@muesli

**Comment by muesli** [comment]
@fzdwx If you bump termenv to v0.13.0, please also bump glamour to `master`. A new release will follow soon.

**Comment by fzdwx** [comment]
Ok, thinks! I'm looking forward to it.
