### ISSUE TITLE
Mangled newlines in definition lists

### ISSUE THREAD

**Issue by afranke** [charmbracelet/glamour#239]
Newlines get mangled after the first item in the list and everything until the end of the list gets shown as definitions for the first term.

```
First term
: Definition one of first term.

Second term
: Definition one of second term.
```

yields

```
  First term
  🠶 Definition one of first term.Second term
  🠶 Definition one of second term.
```

Adding more newlines between items doesn’t help.

**Comment by bashbunni** [comment]
Thanks for reporting, just added to our list :+1:

**Comment by bugabinga** [comment]
A workaround, that should not cause too many issues with other parsers can be to separate the def list items by an escape char `\`.

```markdown
First term
: Definition one of first term.
\
Second term
: Definition one of second term.
```
