### ISSUE TITLE
refactor: replace TableWriter with lipgloss table

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/glamour#254]
Depends on this PR in Lipgloss https://github.com/charmbracelet/lipgloss/pull/218
Would simplify the implementation of our current table rendering solution

**Comment by maxmoehl** [comment]
Would this help resolve #247 or is that a different issue?

**Comment by bashbunni** [comment]
hey @maxmoehl this change should fix a lot of the issues currently have open for glamour tables. That one included
