### ISSUE TITLE
Line feed in vim code block rendered as error

### ISSUE THREAD

**Issue by mmrwoods** [charmbracelet/glamour#257]
Glamour renders \n as visible error when rendering VimL code blocks. This is due to lexer bug in Chroma, now fixed, but yet to be released, combined with the code block error style in Glamour rendering errors with a red background (rather than Chroma default of using red text).

See https://github.com/alecthomas/chroma/issues/827 for more info

Upgrading the Chroma dependency could address this, but the latest stable release, 2.8.0, does not include the fix.

What is the best approach to solving this? Just wait for a stable Chroma release including the fix and then open a PR to bump the Chroma version in Glamour?

**Comment by caarlos0** [comment]
this was fixed on master. thanks! - and sorry for the delay!

**Comment by mmrwoods** [comment]
Great, thanks 👍
