### ISSUE TITLE
Unit tests failed: Rendered output doesn't match!

### ISSUE THREAD

**Issue by Hellseher** [charmbracelet/glamour#276]
Hi,

During review of the failed to build package in Guix we faced with the issue
where unit tests are failed to pass:

Version: v0.2.0
Reported in: https://issues.guix.gnu.org/issue/68311
Reported  by: @artyom-poptsov

Raw output:
[go-github-com-charmbracelet-glamour.txt](https://github.com/charmbracelet/glamour/files/13866780/go-github-com-charmbracelet-glamour.txt)

**Comment by caarlos0** [comment]
can't reproduce locally or on our CI
