### ISSUE TITLE
dracula theme does not load correctly

### ISSUE THREAD

**Issue by amanger-qual** [charmbracelet/glamour#298]
**Describe the bug**
When loading the dracula theme, the style doesn't match the gallery from the repo. All the headings are green and all other text is washed out gray

**Setup**
Please complete the following information along with version numbers, if applicable.
 - macOS 14.4.1
 - zsh
 - native terminal

**Note**: UTF-8 is being used

**To Reproduce**
I tried various ways to get this to work, but with not success.

Test 1
1. run `glow config`
2. change style variable to `"dracula"`
3. save changes, exit, then open a file in glow

**Note**: The steps below worked for the notty and pink themes

Test 2
1. run `glow -s dracula`
2. open a file

Test 3
1. download dracula.json from the charmbracelet/glamour repo: `curl -o ~/.glow/dracula.json https://raw.githubusercontent.com/charmbracelet/glamour/master/styles/dracula.json`
3. run `glow config`
4. change style variable to `"~/.glow/dracula.json"`
5. save changes, exit, then open a file in glow

**Source Code**
[dracula.json](https://raw.githubusercontent.com/charmbracelet/glamour/master/styles/dracula.json)

**Expected behavior**
I expected the file to appear as show in the glamour gallery 

**Screenshots**
My result
![Screenshot 2024-05-02 at 10 44 07](https://github.com/charmbracelet/glamour/assets/161364879/f99cadc2-3b81-4578-8ef8-efa79319fec6)

Glamour Gallery
![dracula](https://github.com/charmbracelet/glamour/assets/161364879/d214c193-4f29-4874-89db-6d1141f79910)

**Comment by caarlos0** [comment]
cannot repro this on master.
