### ISSUE TITLE
tokyo_night style does not load

### ISSUE THREAD

**Issue by adriangalilea** [charmbracelet/glamour#318]
**Describe the bug**
tokyo_night style does not work for me, I managed to use dracula just fine, but tokyo_night does not work regardless of how I try to use it.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS Debian
 - Shell zsh
 - Terminal Emulator kitty

**To Reproduce**
1. Go to [tokyo_night.json](https://github.com/charmbracelet/glamour/blob/master/styles/tokyo_night.json)
2. put it in your `.config/glow/
3. set `style: "tokyo_night"` as your style
4. `Error: Specified style does not exist: tokyo_night`

Also `glow -s ~/.config/glow/tokyo_night.json` did not work.

**Comment by meowgorithm** [comment]
Thanks for flagging: this should be baked in on the library level (contributors, see https://github.com/charmbracelet/glamour/pull/137 as an example).

**Comment by meowgorithm** [comment]
Oh also, note that this version of Glamour isn't in Glow yet.

**Comment by caarlos0** [comment]
fwiw, on master, passing the file path directly with `-s` works,

**Comment by adriangalilea** [comment]
Ahh, note I used `glow` not `glamour` lol... Not sure if relevant as Glow uses Glamour under the hood, but just to be clear my only tests were on glow.

> Also glow -s ~/.config/glow/tokyo_night.json did not work.

**Comment by caarlos0** [comment]
> Not sure if relevant as Glow uses Glamour under the hood, but just to be clear my only tests were on glow.

it does! I did test it on glow master, and it worked too.

The semantics of copying a theme into the configuration folder and then referencing it afaik are not implemented

**Comment by adriangalilea** [comment]
> > Not sure if relevant as Glow uses Glamour under the hood, but just to be clear my only tests were on glow.
> 
> it does! I did test it on glow master, and it worked too.
> 
> The semantics of copying a theme into the configuration folder and then referencing it afaik are not implemented

What do you mean?

I used dracula and worked, but tokyo_night doesn't

**Comment by caarlos0** [comment]
dracula is already embedded in glamour
