### ISSUE TITLE
Indented code block is not rendered as code block

### ISSUE THREAD

**Issue by skatkov** [charmbracelet/glamour#372]
**Is your feature request related to a problem? Please describe.**
CommonMark Spec offers two ways to define a code block:

1. [Fenced code blocks](https://spec.commonmark.org/0.31.2/#fenced-code-blocks) 
2. [Indented code blocks](https://spec.commonmark.org/0.31.2/#indented-code-blocks)

Fenced code block's seem to be working well, but indented code block are not working. 

**Describe the solution you'd like**
I took an `examples/artichokes/artichokes.md` file and added indented code block.

```

    module Main where

    import Data.List (intercalate)

    hello :: String -> String
    hello s = "Hello, " <> s <> "."

    main :: IO ()
    main = putStrLn
        $ intercalate "\n"
        $ hello <$> [ "artichoke", "alcachofa" ]

***

_Alcachofa_, if you were wondering, is artichoke in Spanish.
```

Running a following a `go run . auto` in examples/artichokes folder shows that indented code was not formatted as code block.

![Screenshot From 2024-12-16 16-35-24](https://github.com/user-attachments/assets/e3abb8de-41f6-484a-bcdd-c80446df05c7)

I tried a markdown formatted included with Zed and indented code was formatted as expected.

![Screenshot From 2024-12-16 16-37-39](https://github.com/user-attachments/assets/2112dadc-b9ec-4443-9999-6ba767efa9bc)

**Additional context**
I'm filling this issue with glamour, but this could be related to `goldmark` dependency that glamour is using. To be frank, I haven't tested it with goldmark yet.

[goldmark-highlight](https://github.com/yuin/goldmark-highlighting) supports only fenced code as well.

A lot of code samples on github are shown as `indented code blocks`, so if anyone uses glow for to read through github repo documentation - it's very likely that most of the code will not be highligthed.

**Comment by skatkov** [comment]
I found an example of code block renderer that works with indents.

https://salsa.debian.org/lintian/lintian-ssg/-/blob/main/markdown/code_block_renderer.go?ref_type=heads

**Comment by n-peugnet** [comment]
> I found an example of goldmark code block renderer that works with indents.
> 
> https://salsa.debian.org/lintian/lintian-ssg/-/blob/main/markdown/goldmark_ext/code_block.go

Hi, I'm here by pure coincidence, my implementation of the indented codeblock parser is simply a modified version of [goldmark's indented code block parser](https://github.com/yuin/goldmark/blob/master/parser/code_block.go) (as stated in the first line of the file), that supports non-commonmark-compliant indentations of less than 4 spaces.
So goldmark already supports commonmark-compliant codeblocks, with an indentation of 4 spaces.

It seems to me that the indented codeblock is correctly parsed in your example. It simply does not have the highlighting, which is normal for an indented codeblock, as the language cannot be specified.

**Comment by skatkov** [comment]
@n-peugnet thanks for a post.

Indeed, I removed `haskell` and both code blocks became identical. I assumed, that goldmark will attempt to guess which syntax was in the code block...and highlight appropriately.

**Comment by n-peugnet** [comment]
> I assumed, that goldmark will attempt to guess which syntax was in the code block...and highlight appropriately.

I, for one, really dislike "guessed highlighting". It is almost always incorrect and thus shows invalid highlighting which is very disturbing. If I want highlighting, then I use a fenced code block and select the highlight I want.

In fact, GitHub that you previously cited, does not do "guessed highlight", so the current output matches what you would have had on GitHub:


```haskell
module Main where

import Data.List (intercalate)

hello :: String -> String
hello s = "Hello, " <> s <> "."

main :: IO ()
main = putStrLn
    $ intercalate "\n"
    $ hello <$> [ "artichoke", "alcachofa" ]
```

    module Main where

    import Data.List (intercalate)

    hello :: String -> String
    hello s = "Hello, " <> s <> "."

    main :: IO ()
    main = putStrLn
        $ intercalate "\n"
        $ hello <$> [ "artichoke", "alcachofa" ]

**Comment by skatkov** [comment]
@n-peugnet it's an interesting remark.

Come to think of it, even if I wanted to guess the language defined within a code block - it's not really Glamours responsibility to do that. I'll close down this issue.

In my use of glamour render, it often happens that code blocks are intended and not highlighted. I'll check what I can do on my end or maybe generated markdown could be improved. 

It's a good pure coincidence that you dropped by.
