### ISSUE TITLE
Feature request: consider using functional options

### ISSUE THREAD

**Issue by twpayne** [charmbracelet/glamour#41]
Thank you for this really nice project! I'd like to use it in [chezmoi](https://github.com/twpayne/chezmoi) to replace chezmoi's existing [very crude Markdown-to-text renderer](https://github.com/twpayne/chezmoi/blob/61611b5ed4972184c3cc6e88767e074fa91964fa/internal/extract-helps/main.go#L132-L247).

Currently glamour provides a number of constructors, including [`NewTermRenderer`](https://godoc.org/github.com/charmbracelet/glamour#NewTermRenderer) and [`NewTermRendererFromBytes`](https://godoc.org/github.com/charmbracelet/glamour#NewTermRendererFromBytes). Would you consider using [functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) instead? This has a number of advantages, notably around simplified APIs (fewer constructors) and much greater future extensibility.

I would be happy to submit a PR to implement this if you agree.

**Comment by muesli** [comment]
Definitely _not_ opposed! Looking forward to your PR!
