### ISSUE TITLE
Inter-word spaces are incorrectly stripped from link text

### ISSUE THREAD

**Issue by twpayne** [charmbracelet/glamour#42]
The input markdown:

```
If you want to make a more significant change, please first [open an
issue](https://github.com/twpayne/chezmoi/issues/new) to discuss the change that
you want to make. Dave Cheney gives a [good
rationale](https://dave.cheney.net/2019/02/18/talk-then-code) as to why this is
important.
```

with the default `dark` style is rendered as:

<img width="584" alt="glamour-spaces" src="https://user-images.githubusercontent.com/6942/71524693-89dfc280-28c6-11ea-9d45-c4f5a5ff9700.png">

Note that `open an issue` is rendered as `open anissue` and `good rationale` is rendered as `goodrationale`. In both cases, inter-word spaces are stripped but should not be.

The full input markdown document that demonstrates this error can be found [here](https://raw.githubusercontent.com/twpayne/chezmoi/a402f9eba1245b45de1aa0b05dda4b35c164f345/docs/CONTRIBUTING.md).

**Comment by muesli** [comment]
Fixed by 8405e35.

**Comment by twpayne** [comment]
Thanks very much for the super-fast fixes! chezmoi has now switched to using glamour for rendering its help and docs (https://github.com/twpayne/chezmoi/pull/537).

**Comment by muesli** [comment]
@twpayne That's fantastic! Thank you for reporting the problems you ran into!
