### ISSUE TITLE
Trouble rendering bold, italics and underline in headers

### ISSUE THREAD

**Issue by meowgorithm** [charmbracelet/glamour#5]
When set on a header bold, italics and underline only seem to only affect the prefix. Given the following…

```markdown
# Hello

## Hello

### Hello

#### Hello

##### Hello

###### Hello
```

```json
{
    "heading": {
        "underline": true,
        "bold": true,
        "italic": true
    },
    "h1": { "prefix": "#" },
    "h2": { "prefix": "##" },
    "h3": { "prefix": "###" },
    "h4": { "prefix": "####" },
    "h5": { "prefix": "#####" },
    "h6": { "prefix": "######" }
}
```

…I'm getting the following output:

<img width="181" alt="Screen Shot 2019-12-18 at 11 04 50 PM" src="https://user-images.githubusercontent.com/25087/71144211-3f39b880-21eb-11ea-846c-ab76abdbb424.png">

This is consistent across MacOS Terminal, Kitty and iTerm2 on MacOS.

**Comment by muesli** [comment]
Fixed by 6feb55b.
