### ISSUE TITLE
Suggestion: define default styles in Go, not JSON

### ISSUE THREAD

**Issue by twpayne** [charmbracelet/glamour#50]
Currently, glamour has a number of [standard styles](https://github.com/charmbracelet/glamour/tree/master/styles) defined in JSON files. This has a number of side-effects:

* glamour needs a module and an extra build step (currently [`statik`](github.com/rakyll/statik) to make these JSON files available in the glamour library. The build step needs to be re-run manually whenever any of the style JSON files are modified for the changes to take effect.
* The JSON files are not parsed until they are loaded, i.e. at runtime. There is very little sanity checking: for example, a mis-spelled property will be silently ignored and will instead get the default zero value. Any error in the JSON file will only be raised when it is first used.
* The standard styles are not exported from the glamour package in any way, so any application wanting to use a slightly-modified standard style needs to duplicate the style completely.

In short, the current process is:

    JSON style file -> statik build step -> read JSON from statik at runtime -> parse JSON at runtime -> Go style struct

Would you consider a PR that replaces this with:

    Go style struct

?

Specifically, I propose to:

1. Maintain the current API.
2. Replace the JSON style files with equivalent Go struct literals as exported variables.
3. Remove the use of `statik`.

This would have the following advantages:

1. Standard styles would be directly available to users.
2. Styles would be checked by the compiler at build time.
3. The build process would be simplified, without manual steps.

The only disadvantage that I see is that Go struct literals are more verbose than the equivalent JSON style files. Compare [`simple.json`](https://github.com/charmbracelet/glamour/blob/1c6d016307e4518a82ee6a212984c951eaac9bd5/styles/simple.json) with the near-equivalent [Go struct literal](https://github.com/twpayne/chezmoi/blob/0d2c73d76704c78a6da2a28bc2ca63a8d7d0c66b/internal/chezmoi/styleconfig.go#L5-L104). However, the verbosity would only be noticed by the glamour authors.

Would you accept such a PR?

**Comment by muesli** [comment]
Yes, absolutely! The initial upside for supporting JSON definitions was it being easier and faster to create some default styles, as changing them didn't involve a build step (you could just run `glow -s mystyle.json` to test your changes). However as we have as established these default styles now, I agree we should really integrate them exactly as you propose.
