### ISSUE TITLE
Suggestion: disable coveralls.io coverage tests (not reporting)

### ISSUE THREAD

**Issue by twpayne** [charmbracelet/glamour#51]
At the time of writing, CI for `master` is failing because [`coveralls.io` considers a coverage change of -6.7% to be a failure](https://coveralls.io/builds/27859234). In this case, the coverage drop seems to be related to the way that coverage is reported, not because of any actual change in coverage.

Code coverage is a fun and useful metric, but is overly simplistic for many cases and particularly problematic for Go, where high code coverage requires extra effort to cover all the `err != nil` cases.

Suggestion: configure `coveralls.io` so that it only reports build failures for very significant drops in coverage, say -20%.

**Comment by muesli** [comment]
I've just adjusted the coveralls.io settings to be a bit more lenient when it comes to coverage drops. Thanks for your suggestion!
