### ISSUE TITLE
Odd rendering of table

### ISSUE THREAD

**Issue by mathomp4** [charmbracelet/glamour#60]
All,

First let me say I do love `glow`. Just learned about it recently and it's one less reason I don't need to spawn a browser when editing Markdown (which I'm still learning).

However, I noticed that for some reason a table of mine is rendering...oddly. And I don't know why. The file in question is this [README.md](https://github.com/GEOS-ESM/ESMA-Baselibs/blob/master/README.md). When I run it through `glow`, the entries for three of the rows have odd/different justification:
<img width="423" alt="Screen Shot 2020-01-12 at 1 45 52 PM" src="https://user-images.githubusercontent.com/2982494/72223898-edfabb80-3541-11ea-8597-88cb94ba81a3.png">
I tried looking in vim with `:set list` on, but I don't see any odd characters in those rows. Any ideas on what I might have done?

**Comment by meowgorithm** [comment]
To elaborate on @muesli’s comment, numbers alright right by default, the same way they would in a spreadsheet. This is a great example of why that isn't always ideal!

**Comment by mathomp4** [comment]
Ohhh. I see it. The others are all two-dot semver versions or just plain ol' strings. It's not like it hurts anything, but it just struck me as odd. :smile:

**Comment by arl** [comment]
#87 Hello there, great package here.

Is there an ETA for fixing this? I could help if that's something you'd like to see fix soon. I know I would :-)

**Comment by muesli** [comment]
I'm afraid I still haven't looked into it, so no ETA at this point. Help is always appreciated though!

**Comment by muesli** [comment]
To elaborate a bit more: currently we let the table renderer automatically detect column alignments, which is probably causing this issue. I think we should try to tackle this along with #65 and stick to a fixed alignment as specified in the markdown's table header.

**Comment by arl** [comment]
Sounds great. Yes a fixed alignment would fix that. Later it could be improved with adding support to different alignments but for now, sticking with a consistent alignment, whatever it is, would do the trick.
