### ISSUE TITLE
Code block not displayed if EOL char is CRLF

### ISSUE THREAD

**Issue by enr** [charmbracelet/glamour#63]
Hi, thank you for this tool.
I noticed a problem in the display of the code blocks when the end of line char is set to the Windows' one (CRLF).

(Probably, this issue should be redirected to the Markdown library Glow is using)

To reproduce just try this text (setting the appropriate EOL):

```
    # test

    test

    ```
    test test 
    ```
```
Cheers, Enrico

**Comment by muesli** [comment]
Fixed upstream and bumped dependency in glamour & glow!
