### ISSUE TITLE
Importing this project should not write ANSI escape sequences by itself

### ISSUE THREAD

**Issue by mislav** [charmbracelet/glamour#64]
After https://github.com/charmbracelet/glamour/commit/ac879be81a2a7a8b99492b21d308741c94262872, this project invokes `termenv.HasDarkBackground()` in `init()`, which results in ANSI escape sequences being written to inspect the user's terminal https://github.com/muesli/termenv/blob/aeb2025df63674997334c029ae9b5db7297da9d4/termenv_unix.go#L76

This interferes with our app that imports Glamour for commands that don't even make any use of Glamour output.

Whether it interferes or not, ideally, this library should not interact with the terminal in any way until it's used via an explicit invocation. I see the fact that this is being done on `init()` as generally surprising and potentially harmful.

Discovered by @avdv in https://github.com/cli/cli/issues/647#issuecomment-601689875 
/cc @muesli

**Comment by muesli** [comment]
Agreed, we'll change that. Ideally, we'll also fix the underlying issue, though. The idea behind it, is that glamour automatically adjusts to terminals with a light background color, which I imagine is a feature you probably/eventually want in `cli`.

**Comment by mislav** [comment]
> The idea behind it, is that glamour automatically adjusts to terminals with a light background color, which I imagine is a feature you probably/eventually want in `cli`.

Sure, I understand the idea! I just strongly believe that

* This should not be done on `init()` of your library
* If we explicitly ask for a _specific_ style (either "dark" or "light") at runtime then auto-detection should never be performed

I think that auto-detection should only ever be performed at runtime if someone invoked Glamour and asked for the "auto" (default) style.

**Comment by muesli** [comment]
Again, agreed, that was a bit short-sighted.

**Comment by muesli** [comment]
@mislav Ok, I've changed glamour to not determine the auto style configuration on init, but only when initialized with the `WithAutoStyle` renderer option in 301d3bc.
