### ISSUE TITLE
 Request: align text in the columns

### ISSUE THREAD

**Issue by tredoe** [charmbracelet/glamour#65]
Please consider to add the Github's extension to display data in rows and columns. It allows align text in the columns to the left, right, or center by adding a colon (:) to the left, right, or on both side of the hyphens within the header row.

https://www.markdownguide.org/extended-syntax/  
https://github.github.com/gfm/#tables-extension-

**Comment by muesli** [comment]
Thanks for reporting! Consolidating tickets, see #117.
