### ISSUE TITLE
Options to preserve the hard line break while render

### ISSUE THREAD

**Issue by sibis** [charmbracelet/glamour#70]
Consider the string input as
in := "This is a simple example of glamour! 
Check out"

executing this,
`out, err := glamour.Render(in, "dark")
fmt.Print(out)`

It gets printed in one line. I would like to preserve the hard line break while rendering to get the result as the input.

**Comment by muesli** [comment]
Agreed, we should make re-flowing the text optional.

**Comment by ShubhankarKG** [comment]
@muesli would this stuff work ? I'm just curious since I'm on the same boat as the OP is.

```go
func NewTermRenderer(options ...TermRendererOption) (*TermRenderer, error) {
	tr := &TermRenderer{
		md: goldmark.New(
			goldmark.WithExtensions(
				extension.GFM,
				extension.DefinitionList,
			),
			goldmark.WithParserOptions(
				parser.WithAutoHeadingID(),
			),
                       //  Changed config here.
                       goldmark.WithRendererOptions( 
                               html.WithHardWraps(),
                       ),
		),
	// Rest of the function here
}
```

**Comment by ShubhankarKG** [comment]
@muesli @meowgorithm Any updates here ?

**Comment by ShubhankarKG** [comment]
Any updates still? @muesli

**Comment by muesli** [comment]
Sorry, no updates yet. Have you tried your own patch? Does it work? If so, please send a PR. Otherwise this ticket will automatically get updated as soon as we're (or someone else) is working on it!

**Comment by muesli** [comment]
This is now an option and has been merged to master. Thank you @wilso199!
