### ISSUE TITLE
Link underlines display error after terminal window resize

### ISSUE THREAD

**Issue by Afanyiyu** [charmbracelet/glamour#76]
After Terminal Window Resize, the underlines of the links in the file extended to the end of the line.

Example:

```sh
gh repo view koishijs/koishi
```

![image](https://user-images.githubusercontent.com/20179549/93657380-fd34f000-fa64-11ea-9b04-6da507ce5c9a.png)

This displays normally, but after resizing the window:

![image](https://user-images.githubusercontent.com/20179549/93657386-0c1ba280-fa65-11ea-9367-65037a7068a0.png)

There was a display error.

**Comment by Afanyiyu** [comment]
It seems that this error will only appear on Windows console host (`conhost.exe`).

**Comment by muesli** [comment]
This looks like a bug in the terminal, not glamour.
