### ISSUE TITLE
Markdown's table centering does not work

### ISSUE THREAD

**Issue by jokefrelon** [charmbracelet/glamour#87]
Although it is not a big problem, but hope that the glow becomes better 😉

**Comment by muesli** [comment]
I'd like to keep this open, this is still something I plan to work on.

**Comment by jokefrelon** [comment]
> I'd like to keep this open, this is still something I plan to work on.

Hahaha ok ！You are very dedicated😁

**Comment by muesli** [comment]
Consolidating tickets, see #117.
