### ISSUE TITLE
in charmbracelet/glamour use muesli/termenv and olekukonko/tablewriter together got broken table

### ISSUE THREAD

**Issue by ffit8** [charmbracelet/glamour#95]
NIM

**Comment by muesli** [comment]
Can you try to be a bit more specific, please? What exactly is broken?

**Comment by ffit8** [comment]
When rendering table with olekukonko/tablewriter, and using muesli/termenv to change text highlight, and display the table with charmbracelet/glamour, I got a broken table. Inspired by code in: https://github.com/charmbracelet/bubbles/issues/12

**Comment by muesli** [comment]
Could you provide some code and a screenshot of this, so I can try to reproduce it? Thank you!

**Comment by muesli** [comment]
I'm afraid I'm not sure what exact behavior you're seeing. Closing until we have more information.
